name = "fortune"
main = "src/index.ts"
compatibility_date = "2024-10-19"
compatibility_flags = [ "nodejs_compat" ]

assets = { directory = "public" }

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
