name = "fortune"
main = "src/index.ts"
compatibility_date = "2024-10-19"
compatibility_flags = [ "nodejs_compat" ]

assets = { directory = "public" }

workers_dev = true

# Default environment variables (development)
[vars]
USE_FLARESOLVERR = "false"
FLARESOLVERR_URL = "http://localhost:8191/v1"

[env.staging]
vars = { ENVIRONMENT = "staging" }

[env.production]
vars = { ENVIRONMENT = "production" }

[observability.logs]
enabled = true